/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef _Included_com_qvod_player_tools_DeviceInfo
#define _Included_com_qvod_player_tools_DeviceInfo

#include <jni.h>
#include <android/log.h>
#define  LOG_TAG    "macAddr"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

#define CLASS com_nevin_dmeo_jnimac_jni_MacAddr
#define CLASS_PATH_NAME "com/nevin/dmeo/jnimac/jni/MacAddr"
#define JNI_FUNC(FUN) Java_##CLASS##_##FUN


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nevin_dmeo_jnimac_jni_MacAddr
 * Method:    getMacAddr
 * Signature: (Landroid/content/Context;)Ljava/lang/String;
 */
jstring JNI_FUNC(getMacAddr)(JNIEnv *, jclass, jobject);

jobject getWifiManagerObj(JNIEnv *env, jclass clz, jobject jobj);

jobject getWifiInfoObj(JNIEnv *env, jobject wifiMgrObj);

char* getMacAddress(JNIEnv *env, jobject wifiInfoObj);

bool enableWifi(JNIEnv *env, jobject wifiMgrObj);

bool disableWifi(JNIEnv *env, jobject wifiMgrObj);

#ifdef __cplusplus
}
#endif

#endif
